name: Flutter iOS Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Verificar Flutter
        run: flutter doctor -v

      - name: Instalar dependências
        run: flutter pub get

      - name: Analisar projeto
        run: flutter analyze

      - name: Rodar testes
        run: flutter test
